apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-subscriber
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-subscriber    
  template:
    metadata:
      labels:
        app: redis
        app.kubernetes.io/name: redis-subscriber
    spec:
      containers:
      - name: redis-subscriber
        image: master-node:31320/redis-sub:latest
      imagePullSecrets:
      - name: regcred