apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis-publisher
  labels:
    app: redis
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-publisher    
  template:
    metadata:
      labels:
        app: redis
        app.kubernetes.io/name: redis-publisher
    spec:
      containers:
      - name: redis-publisher
        image: master-node:31320/redis-pub:latest
      imagePullSecrets:
      - name: regcred